In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/creditcard.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [3]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [5]:
df.shape

(284807, 31)

In [9]:
print(df.isnull().sum().max())

0

In [11]:
counts = df['Class'].value_counts()
print(counts)

Class
0    284315
1       492
Name: count, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler

y = df['Class']
X = df.drop(columns=['Class','Time'])

X_train_full , X_test , y_train_full , y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train, X_val, y_train, y_val = train_test_split(
    X_train_full, y_train_full, test_size=0.2, random_state=42, stratify=y_train_full
)

scaler = RobustScaler()

X_train['Amount'] = scaler.fit_transform(X_train[['Amount']])
X_val['Amount']   = scaler.transform(X_val[['Amount']])
X_test['Amount']  = scaler.transform(X_test[['Amount']])

print("Split shapes:")
print(f"X_train: {X_train.shape} | Fraud cases: {y_train.sum()}")
print(f"X_val:   {X_val.shape}   | Fraud cases: {y_val.sum()}")
print(f"X_test:  {X_test.shape}  | Fraud cases: {y_test.sum()}")

Split shapes:
X_train: (182276, 29) | Fraud cases: 315
X_val:   (45569, 29)   | Fraud cases: 79
X_test:  (56962, 29)  | Fraud cases: 98

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, average_precision_score, confusion_matrix

baseline_lr = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
baseline_lr.fit(X_train,y_train)

lr_val_probs = baseline_lr.predict_proba(X_val)[:, 1]
lr_val_preds = baseline_lr.predict(X_val)

print("=== Logistic Regression Baseline (Validation Set) ===")
print(classification_report(y_val, lr_val_preds, digits=4))
print(f"PR-AUC (Average Precision): {average_precision_score(y_val, lr_val_probs):.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_val, lr_val_preds))

=== Logistic Regression Baseline (Validation Set) ===
              precision    recall  f1-score   support

           0     0.9998    0.9752    0.9874     45490
           1     0.0585    0.8861    0.1098        79

    accuracy                         0.9751     45569
   macro avg     0.5292    0.9307    0.5486     45569
weighted avg     0.9982    0.9751    0.9858     45569

PR-AUC (Average Precision): 0.6782
Confusion Matrix:
 [[44364  1126]
 [    9    70]]

In [23]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models ,callbacks
from sklearn.metrics import classification_report , confusion_matrix , average_precision_score

tf.keras.utils.set_random_seed(42)

neg_count = int((y_train == 0).sum())
pos_count = int((y_train == 1).sum())
total = len(y_train)

# Fraud instances get scaled up in the loss function
weight_for_0 = (1 / neg_count) * (total / 2.0)
weight_for_1 = (1 / pos_count) * (total / 2.0)
class_weights = {0: weight_for_0, 1: weight_for_1}

print(f"Class 0 (Legit) weight: {weight_for_0:.2f}")
print(f"Class 1 (Fraud) weight: {weight_for_1:.2f}\n")


input_features = X_train.shape[1]

fraud_ann = models.Sequential([
    layers.Input(shape=(input_features,)),

    layers.Dense(64 , activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.2),

    layers.Dense(32,activation = 'relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.2),

    layers.Dense(16,activation='relu'),

    layers.Dense(1,activation='sigmoid')
    #we use sigmoid cause it produces the result as betwene 0 and one , it squashes the data

    ])


fraud_ann.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001),
    loss = 'binary_crossentropy',
    metrics =[
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall'),
        tf.keras.metrics.AUC(curve='PR', name='pr_auc')
    ]
)

early_stop = callbacks.EarlyStopping(
    monitor = 'val_pr_auc',
    mode = 'max',
    patience=10,
    restore_best_weights = True,
    verbose=1

)

reduce_lr = callbacks.ReduceLROnPlateau(
    monitor='val_pr_auc',
    mode='max',
    factor=0.5,
    patience=4,
    min_lr=1e-5,
    verbose=1
)


history = fraud_ann.fit(
    X_train,
    y_train,
    validation_data=(X_val , y_val),
    epochs = 40 ,
    batch_size = 2048,
    class_weight = class_weights,
    callbacks = [early_stop , reduce_lr],
    verbose = 1
)

val_probs = fraud_ann.predict(X_val).flatten()
val_preds = (val_probs >= 0.5).astype(int)

ann_pr_auc = average_precision_score(y_val, val_probs)

print("\n=== ANN Performance (Validation Set, Threshold = 0.5) ===")
print(classification_report(y_val, val_preds, digits=4))
print(f"ANN PR-AUC (Average Precision): {ann_pr_auc:.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_val, val_preds))

Class 0 (Legit) weight: 0.50
Class 1 (Fraud) weight: 289.33

Epoch 1/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - loss: 0.3782 - pr_auc: 0.1775 - precision: 0.0054 - recall: 0.9143 - val_loss: 0.3620 - val_pr_auc: 0.6604 - val_precision: 0.0317 - val_recall: 0.8861 - learning_rate: 0.0010
Epoch 2/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2041 - pr_auc: 0.5000 - precision: 0.0256 - recall: 0.9302 - val_loss: 0.1725 - val_pr_auc: 0.6365 - val_precision: 0.0507 - val_recall: 0.8861 - learning_rate: 0.0010
Epoch 3/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.1646 - pr_auc: 0.5001 - precision: 0.0343 - recall: 0.9206 - val_loss: 0.1149 - val_pr_auc: 0.6915 - val_precision: 0.0626 - val_recall: 0.8734 - learning_rate: 0.0010
Epoch 4/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.1513 - pr_auc: 0.5599 - precision: 0.0410 - recall: 0.9270 - val_loss: 0.0974 - val_pr_auc: 0.6984 - val_precision: 0.0606 - val_recall: 0.8861 - learning_rate: 0.0010
Epoch 5/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.1374 - pr_auc: 0.5506 - precision: 0.0407 - recall: 0.9238 - val_loss: 0.0830 - val_pr_auc: 0.7060 - val_precision: 0.0675 - val_recall: 0.8734 - learning_rate: 0.0010
Epoch 6/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.1159 - pr_auc: 0.5939 - precision: 0.0446 - recall: 0.9524 - val_loss: 0.0794 - val_pr_auc: 0.6951 - val_precision: 0.0593 - val_recall: 0.8734 - learning_rate: 0.0010
Epoch 7/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.1074 - pr_auc: 0.6000 - precision: 0.0483 - recall: 0.9556 - val_loss: 0.0691 - val_pr_auc: 0.7221 - val_precision: 0.0691 - val_recall: 0.8734 - learning_rate: 0.0010
Epoch 8/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0961 - pr_auc: 0.6611 - precision: 0.0528 - recall: 0.9492 - val_loss: 0.0617 - val_pr_auc: 0.7154 - val_precision: 0.0762 - val_recall: 0.8734 - learning_rate: 0.0010
Epoch 9/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0960 - pr_auc: 0.6169 - precision: 0.0538 - recall: 0.9587 - val_loss: 0.0674 - val_pr_auc: 0.6786 - val_precision: 0.0606 - val_recall: 0.8734 - learning_rate: 0.0010
Epoch 10/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.1043 - pr_auc: 0.6149 - precision: 0.0470 - recall: 0.9556 - val_loss: 0.0749 - val_pr_auc: 0.6383 - val_precision: 0.0537 - val_recall: 0.8734 - learning_rate: 0.0010
Epoch 11/40
88/90 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0752 - pr_auc: 0.5599 - precision: 0.0529 - recall: 0.9826
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0764 - pr_auc: 0.5994 - precision: 0.0528 - recall: 0.9778 - val_loss: 0.0550 - val_pr_auc: 0.7023 - val_precision: 0.0771 - val_recall: 0.8734 - learning_rate: 0.0010
Epoch 12/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0741 - pr_auc: 0.6398 - precision: 0.0589 - recall: 0.9714 - val_loss: 0.0581 - val_pr_auc: 0.7029 - val_precision: 0.0688 - val_recall: 0.8734 - learning_rate: 5.0000e-04
Epoch 13/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0723 - pr_auc: 0.6738 - precision: 0.0599 - recall: 0.9683 - val_loss: 0.0570 - val_pr_auc: 0.6933 - val_precision: 0.0701 - val_recall: 0.8734 - learning_rate: 5.0000e-04
Epoch 14/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0690 - pr_auc: 0.6214 - precision: 0.0571 - recall: 0.9778 - val_loss: 0.0574 - val_pr_auc: 0.6945 - val_precision: 0.0673 - val_recall: 0.8734 - learning_rate: 5.0000e-04
Epoch 15/40
89/90 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0789 - pr_auc: 0.6676 - precision: 0.0595 - recall: 0.9659
Epoch 15: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0758 - pr_auc: 0.6690 - precision: 0.0560 - recall: 0.9683 - val_loss: 0.0546 - val_pr_auc: 0.7048 - val_precision: 0.0695 - val_recall: 0.8734 - learning_rate: 5.0000e-04
Epoch 16/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0698 - pr_auc: 0.6690 - precision: 0.0606 - recall: 0.9778 - val_loss: 0.0513 - val_pr_auc: 0.7061 - val_precision: 0.0755 - val_recall: 0.8734 - learning_rate: 2.5000e-04
Epoch 17/40
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0801 - pr_auc: 0.6662 - precision: 0.0594 - recall: 0.9683 - val_loss: 0.0539 - val_pr_auc: 0.7038 - val_precision: 0.0735 - val_recall: 0.8734 - learning_rate: 2.5000e-04
Epoch 17: early stopping
Restoring model weights from the end of the best epoch: 7.
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step

=== ANN Performance (Validation Set, Threshold = 0.5) ===
              precision    recall  f1-score   support

           0     0.9998    0.9796    0.9896     45490
           1     0.0691    0.8734    0.1281        79

    accuracy                         0.9794     45569
   macro avg     0.5345    0.9265    0.5589     45569
weighted avg     0.9982    0.9794    0.9881     45569

ANN PR-AUC (Average Precision): 0.7156
Confusion Matrix:
 [[44561   929]
 [   10    69]]